# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

#[build]
#command = "npm run build:preview"
#publish = "public"

[build]
command = "hugo --gc --minify"
publish = "public"


[build.environment]
#GO_VERSION = "1.22.2"
HUGO_VERSION = "0.147.6"   # Use your required Hugo version
NODE_VERSION = "18"

#[context.production]
#command = "npm run build:production"
